services:
  alert-pay-db:
    image: postgres:16
    container_name: alert-pay-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: alertpay
    ports:
      - "5434:5432"
    volumes:
      - ./alertpay-data/db:/var/lib/postgresql/data

  alert-pay:
    build: .
    image: alert-pay
    ports:
      - "4000:4000"
    depends_on:
      - alert-pay-db
    env_file:
      - .env # This line correctly loads environment variables from the .env file
    volumes:
      - .:/app
      - /app/node_modules
      - ./wait-for.sh:/wait-for.sh
      - ./start.sh:/start.sh
    entrypoint: ["sh", "/start.sh"]
    command: ["npm", "run", "sequelize-cli", "db:migrate", "&&", "npm", "start"]

networks:
  default:
    external:
      name: openfinance-net
